#!/usr/bin/env python3
"""Live graph smoke for ttasks shared Copilot agent sessions.

This is intentionally a spike, not a product test. It proves the primitive needed
for a possible Python autotester port while using ttasks itself as the runtime:

- setup is a ``Task.bash(...)`` task,
- baseline and post-agent validation are ``Task.bash(...)`` tasks,
- two ``Task.agent(...)`` turns share one ``CopilotAgentSession``,
- a ``TaskGraph`` wires the whole flow together,
- Copilot SDK built-in tools operate in ``working_directory``.

Run from this repo with local ttasks and the packaged Copilot SDK wheel:

    uv run --python 3.12 \
      --with 'ttasks @ file:///home/cip/src/ttasks' \
      --with github-copilot-sdk \
      python spikes/ttasks_session_smoke.py

Optional:

    TTASKS_SMOKE_MODEL=gpt-5.5 \
    TTASKS_SMOKE_REASONING=medium \
    uv run --python 3.12 \
      --with 'ttasks @ file:///home/cip/src/ttasks' \
      --with github-copilot-sdk \
      python spikes/ttasks_session_smoke.py
"""

from __future__ import annotations

import os
import shlex
import shutil
import sys
import tempfile
import textwrap
from pathlib import Path
from typing import Any

from ttasks import CopilotAgentSession, Task, TaskExecutor, TaskGraph, TaskType


CODEWORD = "blue-sparrow"


def q(value: str | Path) -> str:
    return shlex.quote(str(value))


def create_scratch_dir() -> Path:
    return Path(tempfile.mkdtemp(prefix="ttasks-session-smoke-"))


def event_summary(event: Any) -> str | None:
    """Best-effort compact event formatting across SDK event shapes."""
    event_type = getattr(event, "type", None)
    if event_type:
        return f"[event] {event_type}"
    data = getattr(event, "data", None)
    data_type = type(data).__name__ if data is not None else type(event).__name__
    return f"[event] {data_type}"


def print_event(event: Any) -> None:
    # Keep smoke output conservative. Full event dumps are noisy and SDK-shape
    # dependent; this still proves callbacks are wired.
    summary = event_summary(event)
    if summary:
        print(summary, flush=True)


def build_graph(scratch: Path, python: str) -> tuple[TaskGraph, dict[str, Task]]:
    """Build a ttasks graph for setup -> baseline -> two agent turns -> checks."""
    setup = Task.bash(
        textwrap.dedent(
            f"""
            set -euo pipefail
            cd {q(scratch)}
            git init
            git config user.email smoke@example.invalid
            git config user.name 'ttasks smoke'

            cat > calc.py <<'PY'
            def add(a, b):
                return a - b
            PY

            cat > test_calc.py <<'PY'
            import unittest

            from calc import add


            class CalcTest(unittest.TestCase):
                def test_adds_numbers(self):
                    self.assertEqual(add(2, 3), 5)


            if __name__ == "__main__":
                unittest.main()
            PY

            cat > README.md <<'MD'
            # ttasks shared-session smoke repo

            This repo is generated by autotester/spikes/ttasks_session_smoke.py.
            MD

            cat > .gitignore <<'GI'
            __pycache__/
            *.py[cod]
            GI

            git add .
            git commit -m 'Initial broken calculator'
            """
        ).strip(),
        title="create scratch git repo",
        timeout=60,
    )

    baseline_fails = Task.bash(
        textwrap.dedent(
            f"""
            set -euo pipefail
            cd {q(scratch)}
            if {q(python)} -m unittest -q; then
              echo 'baseline unexpectedly passed' >&2
              exit 1
            fi
            echo 'baseline failed as expected'
            """
        ).strip(),
        title="prove baseline test fails",
        timeout=60,
    )

    inspect = Task.agent(
        textwrap.dedent(
            f"""
            You are operating in a temporary git repository.

            Remember this code word for the rest of this conversation: {CODEWORD}

            Inspect the repository and summarize why the test fails. Do not edit files and do not commit yet.
            """
        ).strip(),
        title="remember codeword and inspect broken repo",
        timeout=240,
    )

    fix = Task.agent(
        textwrap.dedent(
            """
            Fix the failing unittest in this repository by changing the production code only.

            Requirements:
            - Use the built-in repository/file/shell tools available to you.
            - Run `python -m unittest -q` and make sure it passes.
            - Commit the fix.
            - Include the code word I gave you earlier in the commit message.
            - Do not add unrelated files.
            """
        ).strip(),
        title="fix test and commit",
        timeout=600,
    )

    validate = Task.bash(
        textwrap.dedent(
            f"""
            set -euo pipefail
            cd {q(scratch)}
            {q(python)} -m unittest -q
            test "$(git rev-list --count HEAD)" = 2
            git log -1 --pretty=%B | grep -F {q(CODEWORD)}
            test -z "$(git status --short)"
            echo 'post-agent validation passed'
            """
        ).strip(),
        title="validate agent fix",
        timeout=60,
    )

    graph = TaskGraph(title="ttasks shared Copilot session smoke")
    graph.add(setup)
    graph.add(baseline_fails, after=[setup])
    graph.add(inspect, after=[baseline_fails])
    graph.add(fix, after=[inspect])
    graph.add(validate, after=[fix])

    tasks = {
        "setup": setup,
        "baseline_fails": baseline_fails,
        "inspect": inspect,
        "fix": fix,
        "validate": validate,
    }
    return graph, tasks


def print_task_result(name: str, task: Task) -> None:
    print(f"\n[{name}: {task.status.value}] {task.title}")
    result = task.result
    if result is None:
        print("no result")
        return
    if result.output:
        print("stdout/output:")
        print(result.output, end="" if result.output.endswith("\n") else "\n")
    if result.error:
        print("stderr/error:", file=sys.stderr)
        print(result.error, file=sys.stderr)


def main() -> int:
    model = os.environ.get("TTASKS_SMOKE_MODEL", "gpt-5.5")
    reasoning = os.environ.get("TTASKS_SMOKE_REASONING", "medium")
    keep = os.environ.get("TTASKS_SMOKE_KEEP") == "1"

    scratch = create_scratch_dir()
    print(f"scratch repo: {scratch}")
    print(f"model: {model}")
    print(f"reasoning_effort: {reasoning}")

    try:
        graph, tasks = build_graph(scratch, sys.executable)

        with CopilotAgentSession(
            model=model,
            reasoning_effort=reasoning,
            working_directory=str(scratch),
            on_event=print_event,
        ) as session:
            executor = TaskExecutor()
            executor.register(TaskType.AGENT, session.handler())
            graph.run(executor, max_workers=1)

        for name, task in tasks.items():
            print_task_result(name, task)

        if not graph.ok:
            failures = ", ".join(task.title for task in graph.failed)
            blocked = ", ".join(task.title for task in graph.blocked)
            raise RuntimeError(f"graph failed; failed=[{failures}], blocked=[{blocked}]")

        print("\nPASS: ttasks graph + shared Copilot session can support autotester-style agent turns")
        return 0
    finally:
        if keep:
            print(f"keeping scratch repo: {scratch}")
        else:
            shutil.rmtree(scratch, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
